### ISSUE TITLE
Management UI: The policy page displays : error getting policy data

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#114]
To replicate:
Go to http://management-ui.northeurope.cloudapp.azure.com
Go to Policy
![2021-01-04_14h17_00.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/1c933e22-9b9c-4203-ad3b-61aacda465ca)

**Comment by mpigram** [comment]
@gw-sbirch are you able to take a look please? If you need any help from me let me know. This was the same issue Nadege was having before xmas break also.

**Comment by gw-sbirch** [comment]
@mpigram

The service is complaining because of the new configuration option. This should be fixed when develop is merged into main I believe.

A work around might be to add the two options in develop that are not in main.

**Comment by gw-sbirch** [comment]
I have done this, but the config will reset if it is redeployed

**Comment by mpigram** [comment]
Nice one @gw-sbirch - we shouldn't need to be redeploying at this moment. Me and Paul are working on merging dev with main soon, so that should solve this issue.

Did those config changes take long? If not I may get you to do it again if we redeploy

**Comment by mpigram** [comment]
@NadHodeGW can confirm that policies are now appearing and no longer receiving the error, thanks to @gw-sbirch

**Comment by gw-sbirch** [comment]
@mpigram dont take long, I just added these to the policy API deployment:
```

- name: PolicyUpdateServiceUsername
            valueFrom:
              secretKeyRef:
                key: TokenUsername
                name: policyupdateserviceref
          - name: NcfsPolicyUpdateServiceUsername
            valueFrom:
              secretKeyRef:
                key: TokenUsername
                name: policyupdateserviceref
          - name: PolicyUpdateServicePassword
            valueFrom:
              secretKeyRef:
                key: TokenPassword
                name: policyupdateserviceref
          - name: NcfsPolicyUpdateServicePassword
            valueFrom:
              secretKeyRef:
                key: TokenPassword
                name: policyupdateserviceref
```
